item/urls.py
from django.conf.urls import url

from . import views

app_name = "Item"

urlpatterns = [
    url(r'^(?P<region_selected>[-\w]+)/$', views.get_travel_data, name = 'travel_data'),
    url(r'^search/query/$', views.search_result, name='search_travel_data'),
    url(r'^search/keyword/$', views.keyword_result, name='keyword_search'),
    url(r'^search/query/detail/(?P<id>[-\w]+)/$', views.data_detail, name='travel_data_detail')
]

trip/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from home import views as home
from item import views as item




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^item/', item.index),
    url(r'^$', home.index),
    url(r'^region/', include('item.urls', namespace = 'Item')),
]

home/models.py
from django.db import models

# Create your models here.

item/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Itinerary(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    price = models.CharField(max_length=6)
    region = models.CharField(max_length=13)
    agency = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    detail = models.TextField()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_travel_detail(self):
        return reverse('Item:travel_data_detail', args = [self.id])

class Travel_Date(models.Model):
    departure_date = models.DateField()
    status = models.CharField(max_length=10)
    link = models.URLField(blank=False)
    price = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)
    itinerary = models.ForeignKey(Itinerary, on_delete=models.CASCADE)

class TopWord(models.Model):
    word = models.CharField(max_length=128)
    count = models.IntegerField()
    year = models.IntegerField()
    month = models.IntegerField()

home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from item.models import TopWord

# Create your views here.
def index(request):
    top_words = TopWord.objects.all()
    return render(request, 'home/index.html', {'top_words':top_words})
    # return render(request, 'home/index.html', response)

item/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
# from django.template import RequestContext, loader
from .models import *
from functools import reduce
import operator
from django.db.models import Q
import ast
import jieba
import re
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

# Create your views here.

def index(request):
    response = {}
    return render(request, 'item/index.html', response)

def get_travel_data(request, region_selected=None):
    datas = None
    contacts = None
    datas = Itinerary.objects.filter(region = region_selected).order_by('-id')
    paginator = Paginator(datas, 25) 
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)
    travel_dates = Travel_Date.objects.filter(itinerary__in=contacts)
 
    return render(request, 'item/region.html', {'contacts':contacts,'datas': datas, 'region':region_selected, 'travel_dates': travel_dates})

def search_result(request):
    datas=None
    contacts = None
    region = request.GET.get("region")
    startDate = request.GET.get("StartDate")
    endDate = request.GET.get("EndDate")
    # keyWords = request.GET.get("KeyWords")
    search = request.GET.get("KeyWords").split(' ')
    keyWords = reduce(operator.or_, (Q(title__icontains=x) for x in search))

    
    datas = Itinerary.objects.filter(Q(region__contains = region)&
                                        Q(travel_date__departure_date__range=(startDate, endDate))&
                                        Q(keyWords)).order_by('-id').distinct()
    paginator = Paginator(datas, 20) 
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)
    travel_dates = Travel_Date.objects.filter(itinerary__in=contacts)
    return render(request, 'item/region.html', {'datas':datas, 'contacts': contacts, 'travel_dates': travel_dates, 'region': region})

def data_detail(request, id):
    data = Itinerary.objects.get(id = id)
    try:
        detail = ast.literal_eval(data.detail)
    except SyntaxError:
        pass
    except ValueError:
        pass

    region = data.region
    clean_title = re.sub("[〈〉～《》▪￭◆．等日無天 A-Za-z0-9「」ｘ『』•【】\x08;\s+\.\!\<>/_,$%^*(+\"\'+——！，\[\]Xx｜。１２３４５６７８９？、~@#￥%……&*（）＋；〜－)®：●♥★™🏆‧-]",
        "", data.title)
    cut_title = jieba.lcut(clean_title)
    travel_dates = Travel_Date.objects.filter(itinerary=data)
    travel_date = travel_dates[0]
    condition = reduce(operator.or_, (Q(detail__icontains = x) for x in cut_title))
    similar_data = Itinerary.objects.filter(condition).distinct()
    if len(similar_data) >= 5:
        similar_data = list(reversed(similar_data))
        similar_data = similar_data[:5]
    elif len(similar_data) == 0:
        similar_data = ["敬請期待"]
    return render(request, 'item/detail.html', locals())

def keyword_result(request):
    datas=None
    contacts = None
    search = request.GET.get("KeyWords").split(' ')
    keyWords = reduce(operator.or_, (Q(title__icontains=x) for x in search))
    datas = Itinerary.objects.filter(Q(keyWords)).order_by('id')
    paginator = Paginator(datas, 20) 
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)
    travel_dates = Travel_Date.objects.filter(itinerary__in=contacts)
    return render(request, 'item/keyword.html', {'datas':datas, 'contacts': contacts, 'travel_dates': travel_dates, 'KeyWord': search})

templates/item/detail.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <title>YOLO Travel</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/icon" href="{% static "favicon.ico" %}"/>
    <link rel="shortcut icon" type="image/icon" href="{% static "favicon.ico" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/demo.css" %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <style>
      p {
          /* border-left: 6px solid plum; */
          background-color: pink;
          padding: 15px;
      }
      p1 {
          background-color: plum;
          padding: 15px;
      }
      p2 {
          background-color: rgb(160, 171, 221);
          padding: 15px;
      }
      a {
          color:#002080;
          text-decoration:underline;
      }

      table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 90%;
          margin: 50px;
      }


      table#t01 {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 85%;
      }

      table#t02{
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 85%;
      }

      table#t03{
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 90%;
      }

      td{
          border: 2px solid;
          border-color: #dddddd;
          text-align: center;
          padding: 8px;
          color: black;
      }

      td#t01{
          border: 2px solid #ffe6ff;
          text-align: center;
          padding: 8px;
      }

      td#t02{
          border: 2px solid #ccdcff;
          text-align: center;
          padding: 8px;
      }

      td#t03{
          border: 2px solid #ffe6ff;
          background-color: #ccdcff;
          text-align: center;
          padding: 15px;
      }

      th {
          border: 2px;
      }


      tr#t01:nth-child(even) {
          background-color: #ccdcff;
      }

      tr#t03:nth-child(even){
          background-color: #ffe6ff;
      }
      tr#t03:nth-child(odd){
      }

      #topnav {
        overflow: hidden;
        width: 100%;
        position:relative;; /*固定位置定位*/
        top:0; /*距離上方 0 像素*/
        z-index:1; /*重疊時會在其他元素之上*/
      }

      #topnav a {
        float: left;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
      }

      .scheduleRecommendation, .similar {
        text-align: center;
      }

      .cloud{
        background-image: url(http://www.onlygfx.com/wp-content/uploads/2016/10/watercolor-cloud-1.png);
        background-position: center;
        background-repeat: no-repeat;
        background-size: contain;
        height: 150px;
        font-family:monospace;
      }

      body{
        margin:0px;
        padding:0px;
        background-image: url({% static "detailSKY.png" %});
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover;
      }

        .box{padding: 15px ;}
        .span1{width: 200px;padding-right: 10px;position: relative;float: right;}
        .span2{float: right;padding-left: 10px;}
        .form-control{position: absolute;top: 0;}

  </style>
</head>
<body>

  <div id="topnav">
    <a class="navbar-brand" href="http://54.249.170.145"><img src="{% static "yoloicon.png" %}"  width="110" height="40" align="center" valign="center"></a>
    <form class="box" action="{% url "Item:keyword_search" %}" target="_blank">
      <span class="span2">
          <button type="submit" class="btn btn-default" height="20px" font= "normal 18px/20px">Submit</button>
      </span>
      <span class="span1">
          <input type="text" class="form-control" placeholder="Search keywords..." name="KeyWords" style="height: 40px;width: 200px;">
      </span>
    </form>
  </div>

  <div class="cloud">
  <br>
  <br>
  <h3 align="center">簡易行程一覽</h3></div>
  <table>
      <tr>
        <td style="background-color: #ffe6ff;">行程名稱</td>
        <td>{{ data.title }}</td>
      </tr>
      <tr>
        <td style="background-color: #ffe6ff;">行程網址</td>
        <td><a href="{{ travel_date.link }}">{{ travel_date.link }}</a></td>
      </tr>
      <tr>
        <td style="background-color: #ffe6ff;">行程價錢</td>
        <td>
          {% for travel in travel_dates %}
            NT${{travel_date.price}}
          {% endfor %}
        </td>
      </tr>
      <td style="background-color: #ffe6ff;">出發日期</td>
        <td>
          {% for travel in travel_dates %}
            <a href="{{ travel.link }}"> {{ travel.departure_date|date:"m/d/Y" }} </a>
          {% endfor %}
        </td>
  </table>

    <br>
    <br>


  {% if not detail.KeyWords %}
  <div class="scheduleRecommendation">
    <div class="container">
    <div class="col-md-12">
      <div class="cloud">
      <br>
      <br>
      <h2 align="center">Schedule</h2></div>
      <table id='t01'>
      {% for key, value in detail.items %}
        {% if key != 'Keywords' %}
          <tr id='t01'>
            <td id='t01'><strong>{{ key }}</strong></td>
          </tr>
          <tr id='t01'>
            <td id='t01'>{{ value }}</td>
          </tr>
        {% endif %}
      {% endfor %}
      </table>
    </div>
    </div>
    {% else %}
    <div class="scheduleRecommendation">
      <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="cloud">
        <br>
        <br>
        <h2 align="center">Schedule</h2></div>
        <table id='t01'>
        {% for key, value in detail.items %}
          {% if key != 'Keywords' %}
            <tr id='t01'>
              <td id='t01'><strong>{{ key }}</strong></td>
            </tr>
            <tr id='t01'>
              <td id='t01'>{{ value }}</td>
            </tr>
          {% endif %}
        {% endfor %}
        </table>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-6">
        {% for key, value in detail.items %}
          {% if key == 'Keywords' %}
          <div class="cloud">
          <br>
          <br>
            <h2 align="center">{{ key }}</h2></div>
            <table id='t02'>
            <td id='t02'>
            {% for item in value %}
                <ul style="list-style-type:disc">
                    <li>{{ item }}</li>
                </ul>
            {% endfor %}
          {% endif %}
        {% endfor %}
      </td></table>
      </div>
    </div>
    {% endif %}
    
    <div class="similar">
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="cloud">
        <br>
        <br>
        <h2>相似行程</h2></div>
        <table id='t03'>
          {% for item in similar_data %}
              {% if item.id != data.id %}
                <tr id='t03'>
                  <td id='t03'><a href="{{ item.get_travel_detail }}"> {{ item.title }}</a></td>
                </tr>
              {% endif %}
          {% endfor %}

              </table>
      </div>
    </div>
</body>
</html>

templates/item/keyword.html
<!DOCTYPE html>
{% load staticfiles %}

<head>
    <title>YOLO Travel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link rel="icon" type="image/icon" href="{% static " favicon.ico" %}" />
    <link rel="shortcut icon" type="image/icon" href="{% static " favicon.ico" %}" />
    <style>
        .regionName {
            background-image: url({% static "airplaneheart.png" %});
            background-position: 53%;
            background-repeat: no-repeat;
            background-size: contain;
            height: 220px;
            font-family:monospace;
        }
        a {
            float: right;
        }
        b {
            float: right;
        }
        f {
            padding-bottom: 5px;
        }

        #topnav {
            overflow: hidden;
            width: 100%;
            position:relative;; /*固定位置定位*/
            top:0; /*距離上方 0 像素*/
            z-index:1; /*重疊時會在其他元素之上*/
        }

        #topnav a {
            float: left;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        body{
            margin:0px;
            padding:0px;
            background-image: url({% static "regionSKY.jpg" %});
            background-repeat: no-repeat;
            background-position: center;
            background-size: cover;
        }

        .current{
            padding-top: 10px;
            padding-right: 10px;
        }

        .box{padding: 15px ;}
        .span1{width: 200px;padding-right: 10px;position: relative;float: right;}
        .span2{float: right;padding-left: 10px;}
        .form-control{position: absolute;top: 0;}
    </style>
</head>

<body>
  <div id="topnav">
    <a class="navbar-brand" href="http://54.249.170.145"><img src="{% static "yoloicon.png" %}"  width="110" height="40" align="center" valign="center"></a>
    <form class="box" action="{% url "Item:keyword_search" %}" target="_blank">
      <span class="span2">
          <button type="submit" class="btn btn-default" height="20px" font= "normal 18px/20px">Submit</button>
      </span>
      <span class="span1">
          <input type="text" class="form-control" placeholder="Search keywords..." name="KeyWords" style="height: 40px;width: 200px;">
      </span>
    </form>
  </div>

    <div class="container">
        <br>
        <div class="regionName">
            <br>
            <br>
            <br>
            <h3 align="center"><strong>搜尋結果:{{ KeyWord.0 }}</strong></h3>
            </br>
        </div>
        <p align="right" style="font-family:Microsoft JhengHei;">總共有{{datas.count}}筆資料</p>
        <ul class="pagination">
            <span class="current"> Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}. </span>
            <li class="page-item">
                {% if contacts.has_previous %}
                <a class="page-link" href="?page=1&KeyWords={{ KeyWord.0 }}" aria-label="first">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">First</span>
                </a>

            </li>
            <li class="page-item">

                <a class="page-link" href="?page={{ contacts.previous_page_number }}&KeyWords={{ KeyWord.0 }}" aria-label="Previous">
                    <span aria-hidden="true">
                        <</span> <span class="sr-only">Previous
                    </span>
                </a>
                {% endif %}
            </li>

            <li class="page-item">
                {% if contacts.has_next %}
                <a class="page-link" href="?page={{ contacts.next_page_number }}&KeyWords={{ KeyWord.0 }}" aria-label="Next">
                    <span aria-hidden="true">></span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ contacts.paginator.num_pages }}&KeyWords={{ KeyWord.0 }}" aria-label="last">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Last</span>
                </a>
                {% endif %}
            </li>
        </ul>
        {% for data in contacts %}
        <div class="card-deck">
            <div class="card border-secondary mb-3">
                <div class="card-body">
                    <h5 class="card-title" style="font-family:Microsoft JhengHei;">{{data.title}}</h5>
                    {% if data.price != "" %}
                    <h3><b class="badge  badge-success">NT${{data.price}}</b></h3>
                    {% else %}
                    <h3><b class="badge  badge-success">候補</b></h3>
                    {% endif %}
                    {% for travel_date in travel_dates %}
                    {% if travel_date.itinerary.id == data.id %}
                    <h5>
                        <span type="button" class="badge badge-pill badge-primary" data-toggle="popover" data-placement="right"
                            title="{{travel_date.status}}">
                            {{ travel_date.departure_date|date:"m/d/Y" }}
                        </span>
                    </h5>
                    {% endif %}
                    {% endfor %}


                </div>
                <f class="container">
                    <a type="button" href="{{ data.get_travel_detail }}" class="btn btn-info">
                        Info
                    </a>
                </f>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="container">
        <ul class="pagination">
            <span class="current" style="padding-bottom"> Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}. </span>
            <li class="page-item">
                {% if contacts.has_previous %}
                <a class="page-link" href="?page=1&KeyWords={{ KeyWord.0 }}" aria-label="first">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">First</span>
                </a>

            </li>
            <li class="page-item">

                <a class="page-link" href="?page={{ contacts.previous_page_number }}&KeyWords={{ KeyWord.0 }}" aria-label="Previous">
                    <span aria-hidden="true">
                        <</span> <span class="sr-only">Previous
                    </span>
                </a>
                {% endif %}
            </li>

            <li class="page-item">
                {% if contacts.has_next %}
                <a class="page-link" href="?page={{ contacts.next_page_number }}&KeyWords={{ KeyWord.0 }}" aria-label="Next">
                    <span aria-hidden="true">></span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ contacts.paginator.num_pages }}&KeyWords={{ KeyWord.0 }}" aria-label="last">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Last</span>
                </a>
                {% endif %}
            </li>
        </ul>
    </div>
</body>
<!-- <div class="pagination">
    <span class="step-links">
        {% if contacts.has_previous %}
        <a href="?page=1&KeyWords={{ KeyWord.0 }}">&laquo; first</a>
        <a href="?page={{ contacts.previous_page_number }}&KeyWords={{ KeyWord.0 }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
        </span>

        {% if contacts.has_next %}
        <a href="?page={{ contacts.next_page_number }}&KeyWords={{ KeyWord.0 }}">next</a>
        <a href="?page={{ contacts.paginator.num_pages }}&KeyWords={{ KeyWord.0 }}">last &raquo;</a>
        {% endif %}
    </span>
</div> -->

templates/item/region.html
<!DOCTYPE html>
{% load staticfiles %}

<head>
    <title>YOLO Travel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link rel="icon" type="image/icon" href="{% static " favicon.ico" %}" />
    <link rel="shortcut icon" type="image/icon" href="{% static " favicon.ico" %}" />
    <style>
        .regionName {
            background-image: url({% static "airplaneheart.png" %});
            background-position: 53%;
            background-repeat: no-repeat;
            background-size: contain;
            height: 220px;
            font-family:monospace;
        }
        a {
            float: right;
        }
        b {
            float: right;
        }
        f {
            padding-bottom: 5px;
        }

        #topnav {
        overflow: hidden;
        width: 100%;
        position:relative;; /*固定位置定位*/
        top:0; /*距離上方 0 像素*/
        z-index:1; /*重疊時會在其他元素之上*/
        }

        #topnav a {
        float: left;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        }

        body{
            margin:0px;
            padding:0px;
            background-image: url(http://pic1.win4000.com/wallpaper/6/5317e63646b1e.jpg);
            background-repeat: no-repeat;
            background-position: center;
            background-size: cover;
        }

        .current{
            padding-top: 10px;
            padding-right: 10px;
        }

        .box{padding: 15px ;}
        .span1{width: 200px;padding-right: 10px;position: relative;float: right;}
        .span2{float: right;padding-left: 10px;}
        .form-control{position: absolute;top: 0;}
	.card-title {
		overflow: hidden;
		height: 150px;
	}
	.badge-pill {
		float: left;
	}


    </style>
</head>

<body>
  <div id="topnav">
    <a class="navbar-brand" href="http://54.255.238.209"><img src="{% static "yoloicon.png" %}"  width="110" height="40" align="center" valign="center"></a>
    <form class="box" action="{% url "Item:keyword_search" %}" target="_blank">
      <span class="span2">
          <button type="submit" class="btn btn-default" height="20px" font= "normal 18px/20px">Submit</button>
      </span>
      <span class="span1">
          <input type="text" class="form-control" placeholder="Search keywords..." name="KeyWords" style="height: 40px;width: 200px;">
      </span>
    </form>
  </div>

    <div class="container">
        <br>
        <div class="regionName">
            <br>
            <br>
            <br>
            <h2 align="center"><strong>{{region}}</strong></h2>
        </div>
        <p align="right" style="font-family:Microsoft JhengHei;">總共有{{datas.count}}筆資料</p>
        <ul class="pagination">
            <span class="current" > Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}. </span>
            <li class="page-item">
                {% if contacts.has_previous %}
                <a class="page-link" href="?page=1" aria-label="first">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">First</span>
                </a>

            </li>
            <li class="page-item">

                <a class="page-link" href="?page={{ contacts.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">
                        <</span> <span class="sr-only">Previous
                    </span>
                </a>
                {% endif %}
            </li>

            <li class="page-item">
                {% if contacts.has_next %}
                <a class="page-link" href="?page={{ contacts.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">></span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ contacts.paginator.num_pages }}" aria-label="last">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Last</span>
                </a>
                {% endif %}
            </li>
        </ul>
        <div class="row">
        {% for data in contacts %}
	<div class="col-lg-3 col-md-4 col-sm-6">
            <div class="card border-secondary mb-3">
                <div class="card-body">
                    <h5 class="card-title" style="font-family:Microsoft JhengHei;">{{data.title}}</h5>
                    {% for travel_date in travel_dates %}
                    {% if travel_date.itinerary.id == data.id %}
                    <h5>
                        <span type="button" class="badge badge-pill badge-primary" data-toggle="popover" data-placement="right"
                            title="{{travel_date.status}}">
                            {{ travel_date.departure_date|date:"m/d/Y" }}
                        </span>
                    </h5>
                    {% endif %}
                    {% endfor %}
                    {% if data.price != "" %}
                    <h3><b class="badge  badge-success">NT${{data.price}}</b></h3>
                    {% else %}
                    <h3><b class="badge  badge-success">候補</b></h3>
                    {% endif %}

                </div>

                <f class="container">
                    <a type="button" href="{{ data.get_travel_detail }}" class="btn btn-info">
                        Info
                    </a>
                </f>
            </div>
	</div>
        {% endfor %}
        </div>
    </div>
    <div class="container">
      <ul class="pagination">
          <span class="current" > Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}. </span>
          <li class="page-item">
              {% if contacts.has_previous %}
              <a class="page-link" href="?page=1" aria-label="first">
                  <span aria-hidden="true">&laquo;</span>
                  <span class="sr-only">First</span>
              </a>

          </li>
          <li class="page-item">

              <a class="page-link" href="?page={{ contacts.previous_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">
                      <</span> <span class="sr-only">Previous
                  </span>
              </a>
              {% endif %}
          </li>

          <li class="page-item">
              {% if contacts.has_next %}
              <a class="page-link" href="?page={{ contacts.next_page_number }}" aria-label="Next">
                  <span aria-hidden="true">></span>
                  <span class="sr-only">Next</span>
              </a>
          </li>
          <li class="page-item">
              <a class="page-link" href="?page={{ contacts.paginator.num_pages }}" aria-label="last">
                  <span aria-hidden="true">&raquo;</span>
                  <span class="sr-only">Last</span>
              </a>
              {% endif %}
          </li>
      </ul>
    </div>
</body>